### ISSUE TITLE
SignChangeEvent Error

### ISSUE THREAD

**Issue by MackySan** [phaed420/PreciousStones#784]
I get this when making a [Rent] Sign.

[16:00:21] [Server thread/ERROR]: Could not pass event SignChangeEvent to PreciousStones v9.7.1-SNAPSHOT
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[minecraft_server.jar:git-Spigot-899f5ee-1092acb]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-899f5ee-1092acb]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-899f5ee-1092acb]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-899f5ee-1092acb]
at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1817) [minecraft_server.jar:git-Spigot-899f5ee-1092acb]
at net.minecraft.server.v1_8_R1.PacketPlayInUpdateSign.a(SourceFile:43) [minecraft_server.jar:git-Spigot-899f5ee-1092acb]
at net.minecraft.server.v1_8_R1.PacketPlayInUpdateSign.a(SourceFile:10) [minecraft_server.jar:git-Spigot-899f5ee-1092acb]
at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [minecraft_server.jar:git-Spigot-899f5ee-1092acb]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_10-ea]
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) [?:1.7.0_10-ea]
at java.util.concurrent.FutureTask.run(FutureTask.java:166) [?:1.7.0_10-ea]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [minecraft_server.jar:git-Spigot-899f5ee-1092acb]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [minecraft_server.jar:git-Spigot-899f5ee-1092acb]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [minecraft_server.jar:git-Spigot-899f5ee-1092acb]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [minecraft_server.jar:git-Spigot-899f5ee-1092acb]
at java.lang.Thread.run(Thread.java:722) [?:1.7.0_10-ea]
Caused by: java.lang.NullPointerException
at java.util.TreeMap.getEntry(TreeMap.java:342) ~[?:1.7.0_10-ea]
at java.util.TreeMap.get(TreeMap.java:273) ~[?:1.7.0_10-ea]
at net.sacredlabyrinth.Phaed.PreciousStones.managers.LanguageManager.get(LanguageManager.java:112) ~[?:?]
at net.sacredlabyrinth.Phaed.PreciousStones.ChatBlock.format(ChatBlock.java:938) ~[?:?]
at net.sacredlabyrinth.Phaed.PreciousStones.ChatBlock.send(ChatBlock.java:767) ~[?:?]
at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.onSignChange(PSBlockListener.java:1724) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_10-ea]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_10-ea]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_10-ea]
at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0_10-ea]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[minecraft_server.jar:git-Spigot-899f5ee-1092acb]
... 15 more

**Comment by MuroHasegawa** [comment]
I get this Error as well, though it's when I try to change a sign that is someone else's. Also Signs, doors, etc... Don't unlock, I've noticed it more while being in creative or being op'd.

http://pastebin.com/VCMHECy0

**Comment by phaed420** [comment]
This looks to be happening due to a missing key in the language.yml file.  Try deleting it and restarting.

**Comment by MackySan** [comment]
I figured out what was wrong. The rent or buy sign has to be TOUCHING the PreciousStone. Otherwise the error appears.
Maybe a message should appear in game saying "A [Rent]/[Buy] Sign must be touching a PreciousStone."

I thought I would put the stone in the middle of the land and the sign just in the border with a path leading to it but I guess I can do that by making it a cuboid. 

Thanks for replying phaed. Hope this helped and keep up the good work :)
